'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Español
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("logica.Español", GetType(Español).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Fecha.
        '''</summary>
        Friend Shared ReadOnly Property _Date() As String
            Get
                Return ResourceManager.GetString("Date", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Agregar.
        '''</summary>
        Friend Shared ReadOnly Property Add() As String
            Get
                Return ResourceManager.GetString("Add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Administrador:.
        '''</summary>
        Friend Shared ReadOnly Property Administrator_() As String
            Get
                Return ResourceManager.GetString("Administrator:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Fecha Nacimiento:.
        '''</summary>
        Friend Shared ReadOnly Property Birthdate_() As String
            Get
                Return ResourceManager.GetString("Birthdate:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Id Ciudad:.
        '''</summary>
        Friend Shared ReadOnly Property City_Id_() As String
            Get
                Return ResourceManager.GetString("City Id:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Descripción:.
        '''</summary>
        Friend Shared ReadOnly Property Description() As String
            Get
                Return ResourceManager.GetString("Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Descripción:.
        '''</summary>
        Friend Shared ReadOnly Property Description_() As String
            Get
                Return ResourceManager.GetString("Description:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Diagnostico.
        '''</summary>
        Friend Shared ReadOnly Property Diagnosis() As String
            Get
                Return ResourceManager.GetString("Diagnosis", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Enfermedades que puede padecer:.
        '''</summary>
        Friend Shared ReadOnly Property Diseases_you_can_suffer_from_() As String
            Get
                Return ResourceManager.GetString("Diseases you can suffer from:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Medicos.
        '''</summary>
        Friend Shared ReadOnly Property Doctors() As String
            Get
                Return ResourceManager.GetString("Doctors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Delete.
        '''</summary>
        Friend Shared ReadOnly Property Eliminar() As String
            Get
                Return ResourceManager.GetString("Eliminar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Correo:.
        '''</summary>
        Friend Shared ReadOnly Property Email_() As String
            Get
                Return ResourceManager.GetString("Email:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error al iniciar sesión.
        '''</summary>
        Friend Shared ReadOnly Property Failed_to_login() As String
            Get
                Return ResourceManager.GetString("Failed to login", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Primer Nombre:.
        '''</summary>
        Friend Shared ReadOnly Property First_Name_() As String
            Get
                Return ResourceManager.GetString("First Name:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Primer Apellido:.
        '''</summary>
        Friend Shared ReadOnly Property First_Surname_() As String
            Get
                Return ResourceManager.GetString("First Surname:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sexo:.
        '''</summary>
        Friend Shared ReadOnly Property Gender_() As String
            Get
                Return ResourceManager.GetString("Gender:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Se ha modificado.
        '''</summary>
        Friend Shared ReadOnly Property Has_been_successfully_modified() As String
            Get
                Return ResourceManager.GetString("Has been successfully modified", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Altura:.
        '''</summary>
        Friend Shared ReadOnly Property Height_() As String
            Get
                Return ResourceManager.GetString("Height:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Hora.
        '''</summary>
        Friend Shared ReadOnly Property Hour() As String
            Get
                Return ResourceManager.GetString("Hour", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cédula:.
        '''</summary>
        Friend Shared ReadOnly Property Identification_card_() As String
            Get
                Return ResourceManager.GetString("Identification card:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a L O G I N - A D M I N I S T R A D O R.
        '''</summary>
        Friend Shared ReadOnly Property L_O_G_I_N___A_D_M_I_N_I_S_T_R_A_T_O_R() As String
            Get
                Return ResourceManager.GetString("L O G I N - A D M I N I S T R A T O R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a INICIAR SESIÓN.
        '''</summary>
        Friend Shared ReadOnly Property LOG_IN() As String
            Get
                Return ResourceManager.GetString("LOG IN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a M E N U  D E  G E S T I Ó N.
        '''</summary>
        Friend Shared ReadOnly Property M_A_N_A_G_M_E_N_T__M_E_N_U() As String
            Get
                Return ResourceManager.GetString("M A N A G M E N T  M E N U", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modificar.
        '''</summary>
        Friend Shared ReadOnly Property Modify_() As String
            Get
                Return ResourceManager.GetString("Modify:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Mortalidad:.
        '''</summary>
        Friend Shared ReadOnly Property Mortality_() As String
            Get
                Return ResourceManager.GetString("Mortality:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nombre:.
        '''</summary>
        Friend Shared ReadOnly Property Name_() As String
            Get
                Return ResourceManager.GetString("Name:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a O S L E R - Sistema de Telediagnóstico.
        '''</summary>
        Friend Shared ReadOnly Property O_S_L_E_R___System_Of_Remote_Diagnostic() As String
            Get
                Return ResourceManager.GetString("O S L E R - System Of Remote Diagnostic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CONTRASEÑA.
        '''</summary>
        Friend Shared ReadOnly Property PASSWORD() As String
            Get
                Return ResourceManager.GetString("PASSWORD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Pacientes.
        '''</summary>
        Friend Shared ReadOnly Property Patients() As String
            Get
                Return ResourceManager.GetString("Patients", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Patologias.
        '''</summary>
        Friend Shared ReadOnly Property Patologies() As String
            Get
                Return ResourceManager.GetString("Patologies", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Número Puerta:.
        '''</summary>
        Friend Shared ReadOnly Property Port_number_() As String
            Get
                Return ResourceManager.GetString("Port number:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Recomendación:.
        '''</summary>
        Friend Shared ReadOnly Property Recommendation_() As String
            Get
                Return ResourceManager.GetString("Recommendation:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Recomendaciones:.
        '''</summary>
        Friend Shared ReadOnly Property Recommendations_() As String
            Get
                Return ResourceManager.GetString("Recommendations:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Segundo Nombre:.
        '''</summary>
        Friend Shared ReadOnly Property Second_Name_() As String
            Get
                Return ResourceManager.GetString("Second Name:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Segundo Apellido:.
        '''</summary>
        Friend Shared ReadOnly Property Second_Surname_() As String
            Get
                Return ResourceManager.GetString("Second Surname:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Enviar.
        '''</summary>
        Friend Shared ReadOnly Property Send() As String
            Get
                Return ResourceManager.GetString("Send", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Información de la sesión.
        '''</summary>
        Friend Shared ReadOnly Property Session_information() As String
            Get
                Return ResourceManager.GetString("Session information", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Mostrar contraseña.
        '''</summary>
        Friend Shared ReadOnly Property Show_Password() As String
            Get
                Return ResourceManager.GetString("Show Password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Especialidad:.
        '''</summary>
        Friend Shared ReadOnly Property Speciality_() As String
            Get
                Return ResourceManager.GetString("Speciality:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Calle:.
        '''</summary>
        Friend Shared ReadOnly Property Street_() As String
            Get
                Return ResourceManager.GetString("Street:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sintomas.
        '''</summary>
        Friend Shared ReadOnly Property Symptom() As String
            Get
                Return ResourceManager.GetString("Symptom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sintomas que padece.
        '''</summary>
        Friend Shared ReadOnly Property Symptoms_you_suffer_from() As String
            Get
                Return ResourceManager.GetString("Symptoms you suffer from", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Se ha ingresado.
        '''</summary>
        Friend Shared ReadOnly Property The_data_has_been_entered_correctly() As String
            Get
                Return ResourceManager.GetString("The data has been entered correctly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Se han ingresado los datos.
        '''</summary>
        Friend Shared ReadOnly Property The_data_has_been_entered_correctly_() As String
            Get
                Return ResourceManager.GetString("The data has been entered correctly.", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Eliminó los datos correctamente.
        '''</summary>
        Friend Shared ReadOnly Property The_data_was_deleted_correctly() As String
            Get
                Return ResourceManager.GetString("The data was deleted correctly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nombre Usuario:.
        '''</summary>
        Friend Shared ReadOnly Property User_name_() As String
            Get
                Return ResourceManager.GetString("User name:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a USUARIO.
        '''</summary>
        Friend Shared ReadOnly Property USERNAME() As String
            Get
                Return ResourceManager.GetString("USERNAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nombre Usuario:.
        '''</summary>
        Friend Shared ReadOnly Property Username_() As String
            Get
                Return ResourceManager.GetString("Username:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nombre Usuario:.
        '''</summary>
        Friend Shared ReadOnly Property Username__() As String
            Get
                Return ResourceManager.GetString("Username:.", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a USUARIO.
        '''</summary>
        Friend Shared ReadOnly Property USERNAME___() As String
            Get
                Return ResourceManager.GetString("USERNAME:..", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a USUARIO.
        '''</summary>
        Friend Shared ReadOnly Property USUARIO() As String
            Get
                Return ResourceManager.GetString("USUARIO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Peso:.
        '''</summary>
        Friend Shared ReadOnly Property Weight_() As String
            Get
                Return ResourceManager.GetString("Weight:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Bienvenido!.
        '''</summary>
        Friend Shared ReadOnly Property Welcome_() As String
            Get
                Return ResourceManager.GetString("Welcome!", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SI.
        '''</summary>
        Friend Shared ReadOnly Property YES() As String
            Get
                Return ResourceManager.GetString("YES", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
