'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Ingles
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("logica.Ingles", GetType(Ingles).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Administrator:.
        '''</summary>
        Friend Shared ReadOnly Property Administrador_() As String
            Get
                Return ResourceManager.GetString("Administrador:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Add.
        '''</summary>
        Friend Shared ReadOnly Property Agregar() As String
            Get
                Return ResourceManager.GetString("Agregar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Height:.
        '''</summary>
        Friend Shared ReadOnly Property Altura_() As String
            Get
                Return ResourceManager.GetString("Altura:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Welcome!.
        '''</summary>
        Friend Shared ReadOnly Property Bienvenido_() As String
            Get
                Return ResourceManager.GetString("Bienvenido!", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Street:.
        '''</summary>
        Friend Shared ReadOnly Property Calle_() As String
            Get
                Return ResourceManager.GetString("Calle:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Identification card:.
        '''</summary>
        Friend Shared ReadOnly Property Cédula_() As String
            Get
                Return ResourceManager.GetString("Cédula:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a PASSWORD.
        '''</summary>
        Friend Shared ReadOnly Property CONTRASEÑA() As String
            Get
                Return ResourceManager.GetString("CONTRASEÑA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Email:.
        '''</summary>
        Friend Shared ReadOnly Property Correo_() As String
            Get
                Return ResourceManager.GetString("Correo:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Description:.
        '''</summary>
        Friend Shared ReadOnly Property Descripcion_() As String
            Get
                Return ResourceManager.GetString("Descripcion:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Description:.
        '''</summary>
        Friend Shared ReadOnly Property Descripción_() As String
            Get
                Return ResourceManager.GetString("Descripción:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Diagnosis.
        '''</summary>
        Friend Shared ReadOnly Property Diagnostico() As String
            Get
                Return ResourceManager.GetString("Diagnostico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Delete.
        '''</summary>
        Friend Shared ReadOnly Property Eliminar() As String
            Get
                Return ResourceManager.GetString("Eliminar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a the data was deleted correctly.
        '''</summary>
        Friend Shared ReadOnly Property Eliminó_los_datos_correctamente() As String
            Get
                Return ResourceManager.GetString("Eliminó los datos correctamente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Diseases you can suffer from:.
        '''</summary>
        Friend Shared ReadOnly Property Enfermedades_que_puede_padecer_() As String
            Get
                Return ResourceManager.GetString("Enfermedades que puede padecer:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Send.
        '''</summary>
        Friend Shared ReadOnly Property Enviar() As String
            Get
                Return ResourceManager.GetString("Enviar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Failed to login.
        '''</summary>
        Friend Shared ReadOnly Property Error_al_iniciar_sesión() As String
            Get
                Return ResourceManager.GetString("Error al iniciar sesión", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Speciality:.
        '''</summary>
        Friend Shared ReadOnly Property Especialidad_() As String
            Get
                Return ResourceManager.GetString("Especialidad:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Missing data.
        '''</summary>
        Friend Shared ReadOnly Property Faltan_Datos() As String
            Get
                Return ResourceManager.GetString("Faltan Datos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Birthdate:.
        '''</summary>
        Friend Shared ReadOnly Property Fecha_Nacimiento_() As String
            Get
                Return ResourceManager.GetString("Fecha Nacimiento:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a City Id:.
        '''</summary>
        Friend Shared ReadOnly Property Id_Ciudad_() As String
            Get
                Return ResourceManager.GetString("Id Ciudad:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Session information.
        '''</summary>
        Friend Shared ReadOnly Property Información_de_la_sesión() As String
            Get
                Return ResourceManager.GetString("Información de la sesión", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a LOG IN.
        '''</summary>
        Friend Shared ReadOnly Property INICIAR_SESIÓN() As String
            Get
                Return ResourceManager.GetString("INICIAR SESIÓN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a L O G I N - A D M I N I S T R A T O R.
        '''</summary>
        Friend Shared ReadOnly Property L_O_G_I_N___A_D_M_I_N_I_S_T_R_A_D_O_R() As String
            Get
                Return ResourceManager.GetString("L O G I N - A D M I N I S T R A D O R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The data was recorded correctly.
        '''</summary>
        Friend Shared ReadOnly Property Los_datos_se_registraron_correctamente() As String
            Get
                Return ResourceManager.GetString("Los datos se registraron correctamente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MANAGMENT MENU.
        '''</summary>
        Friend Shared ReadOnly Property M_E_N_U_D_E_G_E_S_T_I_Ó_N() As String
            Get
                Return ResourceManager.GetString("M E N U D E G E S T I Ó N", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Doctors.
        '''</summary>
        Friend Shared ReadOnly Property Medicos() As String
            Get
                Return ResourceManager.GetString("Medicos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modify.
        '''</summary>
        Friend Shared ReadOnly Property Modificar() As String
            Get
                Return ResourceManager.GetString("Modificar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Mortality:.
        '''</summary>
        Friend Shared ReadOnly Property Mortalidad_() As String
            Get
                Return ResourceManager.GetString("Mortalidad:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Show Password.
        '''</summary>
        Friend Shared ReadOnly Property Mostrar_contraseña() As String
            Get
                Return ResourceManager.GetString("Mostrar contraseña", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Name:.
        '''</summary>
        Friend Shared ReadOnly Property Nombre_() As String
            Get
                Return ResourceManager.GetString("Nombre:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Username:.
        '''</summary>
        Friend Shared ReadOnly Property Nombre_Medico_() As String
            Get
                Return ResourceManager.GetString("Nombre Medico:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Username:.
        '''</summary>
        Friend Shared ReadOnly Property Nombre_Paciente_() As String
            Get
                Return ResourceManager.GetString("Nombre Paciente:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Username:.
        '''</summary>
        Friend Shared ReadOnly Property Nombre_Usuario_() As String
            Get
                Return ResourceManager.GetString("Nombre Usuario:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Port number:.
        '''</summary>
        Friend Shared ReadOnly Property Número_Puerta_() As String
            Get
                Return ResourceManager.GetString("Número Puerta:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a OSLER-System Of Remote Diagnostic.
        '''</summary>
        Friend Shared ReadOnly Property O_S_L_E_R___Sistema_de_Telediagnóstico() As String
            Get
                Return ResourceManager.GetString("O S L E R - Sistema de Telediagnóstico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Patients .
        '''</summary>
        Friend Shared ReadOnly Property Pacientes() As String
            Get
                Return ResourceManager.GetString("Pacientes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Pathologies.
        '''</summary>
        Friend Shared ReadOnly Property Patologias() As String
            Get
                Return ResourceManager.GetString("Patologias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Weight:.
        '''</summary>
        Friend Shared ReadOnly Property Peso_() As String
            Get
                Return ResourceManager.GetString("Peso:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a First Surname:.
        '''</summary>
        Friend Shared ReadOnly Property Primer_Apellido_() As String
            Get
                Return ResourceManager.GetString("Primer Apellido:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a First Name:.
        '''</summary>
        Friend Shared ReadOnly Property Primer_Nombre_() As String
            Get
                Return ResourceManager.GetString("Primer Nombre:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Recomendation:.
        '''</summary>
        Friend Shared ReadOnly Property Recomendación_() As String
            Get
                Return ResourceManager.GetString("Recomendación:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Recommendations:.
        '''</summary>
        Friend Shared ReadOnly Property Recomendaciones_() As String
            Get
                Return ResourceManager.GetString("Recomendaciones:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The data has been entered correctly.
        '''</summary>
        Friend Shared ReadOnly Property Se_ha_ingresado_correctamente() As String
            Get
                Return ResourceManager.GetString("Se ha ingresado correctamente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Has been successfully modified.
        '''</summary>
        Friend Shared ReadOnly Property Se_ha_modificado_correctamente() As String
            Get
                Return ResourceManager.GetString("Se ha modificado correctamente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The data has been entered correctly.
        '''</summary>
        Friend Shared ReadOnly Property Se_han_ingresado_los_datos_correctamente() As String
            Get
                Return ResourceManager.GetString("Se han ingresado los datos correctamente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Second Surname:.
        '''</summary>
        Friend Shared ReadOnly Property Segundo_Apellido_() As String
            Get
                Return ResourceManager.GetString("Segundo Apellido:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Second Name:.
        '''</summary>
        Friend Shared ReadOnly Property Segundo_Nombre_() As String
            Get
                Return ResourceManager.GetString("Segundo Nombre:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Gender:.
        '''</summary>
        Friend Shared ReadOnly Property Sexo_() As String
            Get
                Return ResourceManager.GetString("Sexo:", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Yes.
        '''</summary>
        Friend Shared ReadOnly Property SI() As String
            Get
                Return ResourceManager.GetString("SI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Symptom.
        '''</summary>
        Friend Shared ReadOnly Property Sintomas() As String
            Get
                Return ResourceManager.GetString("Sintomas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Symptoms you suffer from.
        '''</summary>
        Friend Shared ReadOnly Property Sintomas_que_padece() As String
            Get
                Return ResourceManager.GetString("Sintomas que padece", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a USERNAME.
        '''</summary>
        Friend Shared ReadOnly Property USUARIO() As String
            Get
                Return ResourceManager.GetString("USUARIO", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
