'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Español
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("presentacionGestion.Español", GetType(Español).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Medicos.
        '''</summary>
        Friend Shared ReadOnly Property btn_medico() As String
            Get
                Return ResourceManager.GetString("btn_medico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Paciente.
        '''</summary>
        Friend Shared ReadOnly Property btn_paciente() As String
            Get
                Return ResourceManager.GetString("btn_paciente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sintomas.
        '''</summary>
        Friend Shared ReadOnly Property btn_sint() As String
            Get
                Return ResourceManager.GetString("btn_sint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a PATOLOGIAS.
        '''</summary>
        Friend Shared ReadOnly Property btnpato() As String
            Get
                Return ResourceManager.GetString("btnpato", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a LOGIN - ADMINISTRADOR.
        '''</summary>
        Friend Shared ReadOnly Property label_admin() As String
            Get
                Return ResourceManager.GetString("label_admin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Administrador:.
        '''</summary>
        Friend Shared ReadOnly Property label_admins() As String
            Get
                Return ResourceManager.GetString("label_admins", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Agregar.
        '''</summary>
        Friend Shared ReadOnly Property label_agregar() As String
            Get
                Return ResourceManager.GetString("label_agregar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Altura:.
        '''</summary>
        Friend Shared ReadOnly Property label_altura() As String
            Get
                Return ResourceManager.GetString("label_altura", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Primer Apellido.
        '''</summary>
        Friend Shared ReadOnly Property label_apellido1() As String
            Get
                Return ResourceManager.GetString("label_apellido1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Segundo Apellido:.
        '''</summary>
        Friend Shared ReadOnly Property label_apellido2() As String
            Get
                Return ResourceManager.GetString("label_apellido2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Bienvenido!.
        '''</summary>
        Friend Shared ReadOnly Property label_bienvenida() As String
            Get
                Return ResourceManager.GetString("label_bienvenida", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Calle:.
        '''</summary>
        Friend Shared ReadOnly Property label_calle() As String
            Get
                Return ResourceManager.GetString("label_calle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cedula:.
        '''</summary>
        Friend Shared ReadOnly Property label_cedula() As String
            Get
                Return ResourceManager.GetString("label_cedula", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Id Ciudad:.
        '''</summary>
        Friend Shared ReadOnly Property label_ciudad() As String
            Get
                Return ResourceManager.GetString("label_ciudad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CONTRASEÑA.
        '''</summary>
        Friend Shared ReadOnly Property Label_contra() As String
            Get
                Return ResourceManager.GetString("Label_contra", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Desarrollado por tech-vibe.
        '''</summary>
        Friend Shared ReadOnly Property label_creditos() As String
            Get
                Return ResourceManager.GetString("label_creditos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Descripcion:.
        '''</summary>
        Friend Shared ReadOnly Property label_descrip() As String
            Get
                Return ResourceManager.GetString("label_descrip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Eliminar.
        '''</summary>
        Friend Shared ReadOnly Property label_eliminar() As String
            Get
                Return ResourceManager.GetString("label_eliminar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Correo:.
        '''</summary>
        Friend Shared ReadOnly Property label_email() As String
            Get
                Return ResourceManager.GetString("label_email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Especialidad:.
        '''</summary>
        Friend Shared ReadOnly Property label_especialidad() As String
            Get
                Return ResourceManager.GetString("label_especialidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FECHA:.
        '''</summary>
        Friend Shared ReadOnly Property label_fecha() As String
            Get
                Return ResourceManager.GetString("label_fecha", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Fecha de Nacimiento.
        '''</summary>
        Friend Shared ReadOnly Property label_fnaci() As String
            Get
                Return ResourceManager.GetString("label_fnaci", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a HORA:.
        '''</summary>
        Friend Shared ReadOnly Property label_hora() As String
            Get
                Return ResourceManager.GetString("label_hora", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a INICIAR SESION.
        '''</summary>
        Friend Shared ReadOnly Property label_ingresar() As String
            Get
                Return ResourceManager.GetString("label_ingresar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MENU DE GESTION.
        '''</summary>
        Friend Shared ReadOnly Property label_menu() As String
            Get
                Return ResourceManager.GetString("label_menu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modificar.
        '''</summary>
        Friend Shared ReadOnly Property label_modificar() As String
            Get
                Return ResourceManager.GetString("label_modificar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Mortalidad:.
        '''</summary>
        Friend Shared ReadOnly Property label_mort() As String
            Get
                Return ResourceManager.GetString("label_mort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Mostrar contraseña.
        '''</summary>
        Friend Shared ReadOnly Property label_mostra() As String
            Get
                Return ResourceManager.GetString("label_mostra", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Primer Nombre:.
        '''</summary>
        Friend Shared ReadOnly Property label_nombre1() As String
            Get
                Return ResourceManager.GetString("label_nombre1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Segundo Nombre:.
        '''</summary>
        Friend Shared ReadOnly Property label_nombre2() As String
            Get
                Return ResourceManager.GetString("label_nombre2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nombre de Usuario:.
        '''</summary>
        Friend Shared ReadOnly Property label_nombreus() As String
            Get
                Return ResourceManager.GetString("label_nombreus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Numero de puerta:.
        '''</summary>
        Friend Shared ReadOnly Property label_numpuerta() As String
            Get
                Return ResourceManager.GetString("label_numpuerta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a OSLER-Sistema de Telediagnostico.
        '''</summary>
        Friend Shared ReadOnly Property label_osler() As String
            Get
                Return ResourceManager.GetString("label_osler", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Recomendación:.
        '''</summary>
        Friend Shared ReadOnly Property label_recom() As String
            Get
                Return ResourceManager.GetString("label_recom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sexo:.
        '''</summary>
        Friend Shared ReadOnly Property label_sexo() As String
            Get
                Return ResourceManager.GetString("label_sexo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a USUARIO.
        '''</summary>
        Friend Shared ReadOnly Property Label_Usuario() As String
            Get
                Return ResourceManager.GetString("Label_Usuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Peso:.
        '''</summary>
        Friend Shared ReadOnly Property label_weight() As String
            Get
                Return ResourceManager.GetString("label_weight", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
